language: ruby

script:
  - bundle exec jekyll build
  
after_success:
  - ssh-keyscan -H $HOSTNAME 2>&1 | tee -a $HOME/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_65512bf88938_key -iv $encrypted_65512bf88938_iv -in .travis.d/id-rsa.enc -out .travis.d/id-rsa -d
  - mkdir -p ~/.ssh && mv .travis.d/id-rsa ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - rsync -arv --progress --delete _site/ $USERNAME@$HOSTNAME:www/classes/fall17/TCN-6430/
